spring.application.name=member-registration-site

spring.datasource.url=jdbc:postgresql://localhost:5432/member_db
spring.datasource.username=postgres
spring.datasource.password=Yuutoo4649
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

spring.thymeleaf.cache=false

server.port=8080

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE